### PR TITLE
Gpt 63

### PR DESCRIPTION
**Pull request by Bmogul**
Completed creating graphql endpoint with tests for creating users, also added implementation of it in registrationFrom.jsx
updated auth.js in web/src/ with signUp singIn and signOutUser functions for easy access, along with tests.

### CODE REVIEW

**Comment by Bmogul** [comment]
closes #23

**Review by tanner666 — CHANGES_REQUESTED** [review]
changes look good overall, but need to resolve merge conflicts first

**Review by Bmogul — COMMENTED** [review]
resolved merge conflicts

**Review by tanner666 — APPROVED** [review]
looks good

**Pull request merged**
